[
  {
    "origin": "OpenCV: cv::Exception Class Reference",
    "local": "OpenCV:cv:：异常类引用"
  },
  {
    "origin": "Open Source Computer Vision",
    "local": "开源计算机视觉"
  },
  {
    "origin": "Public Member Functions",
    "local": "公共成员职能"
  },
  {
    "origin": "Public Attributes",
    "local": "公共属性"
  },
  {
    "origin": "List of all members",
    "local": "所有成员的列表"
  },
  {
    "origin": "cv::Exception Class Reference",
    "local": "cv:：异常类引用"
  },
  {
    "origin": "&raquo;",
    "local": "&引用；"
  },
  {
    "origin": "Class passed to an error.",
    "local": "类传递给一个错误。"
  },
  {
    "origin": "More...",
    "local": "更多。。。"
  },
  {
    "origin": "Inheritance diagram for cv::Exception:",
    "local": "cv:：Exception的继承关系图："
  },
  {
    "origin": "Public Member Functions",
    "local": "公共成员职能"
  },
  {
    "origin": "()",
    "local": "()"
  },
  {
    "origin": "(int _code, const",
    "local": "（国际代码，常量）"
  },
  {
    "origin": "&amp;_err, const",
    "local": "&amp；u呃，康斯特"
  },
  {
    "origin": "&amp;_func, const",
    "local": "&amp_函数，常量"
  },
  {
    "origin": "&amp;_file, int _line)",
    "local": "&amp_文件，int\\u行）"
  },
  {
    "origin": "() throw ()",
    "local": "（）抛出（）"
  },
  {
    "origin": "()",
    "local": "()"
  },
  {
    "origin": "() const",
    "local": "（）常数"
  },
  {
    "origin": "throw ()",
    "local": "抛出（）"
  },
  {
    "origin": "Public Attributes",
    "local": "公共属性"
  },
  {
    "origin": "error code",
    "local": "错误代码"
  },
  {
    "origin": "More...",
    "local": "更多。。。"
  },
  {
    "origin": "error description",
    "local": "错误描述"
  },
  {
    "origin": "More...",
    "local": "更多。。。"
  },
  {
    "origin": "source file name where the error has occurred",
    "local": "发生错误的源文件名"
  },
  {
    "origin": "More...",
    "local": "更多。。。"
  },
  {
    "origin": "function name. Available only when the compiler supports getting it",
    "local": "函数名。仅当编译器支持获取时才可用"
  },
  {
    "origin": "More...",
    "local": "更多。。。"
  },
  {
    "origin": "line number in the source file where the error has occurred",
    "local": "发生错误的源文件中的行号"
  },
  {
    "origin": "More...",
    "local": "更多。。。"
  },
  {
    "origin": "the formatted error message",
    "local": "格式化的错误消息"
  },
  {
    "origin": "More...",
    "local": "更多。。。"
  },
  {
    "origin": "Detailed Description",
    "local": "详细说明"
  },
  {
    "origin": "Class passed to an error.",
    "local": "类传递给一个错误。"
  },
  {
    "origin": "This class encapsulates all or almost all necessary information about the error happened in the program. The exception is usually constructed and thrown implicitly via CV_Error and CV_Error_ macros.",
    "local": "这个类封装了关于程序中发生的错误的所有或几乎所有必要的信息。异常通常是通过CV\\ u Error和CV\\ u Error\\宏隐式构造和抛出的。"
  },
  {
    "origin": "See also",
    "local": "另请参见"
  },
  {
    "origin": "Examples:",
    "local": "示例："
  },
  {
    "origin": ", and",
    "local": "，和"
  },
  {
    "origin": ".",
    "local": "."
  },
  {
    "origin": "Constructor &amp; Destructor Documentation",
    "local": "建造商和；析构函数文档"
  },
  {
    "origin": "&#9670;&nbsp;",
    "local": "&#9670;&nbsp；"
  },
  {
    "origin": "Exception()",
    "local": "异常（）"
  },
  {
    "origin": "[1/2]",
    "local": "[1/2]"
  },
  {
    "origin": "cv::Exception::Exception",
    "local": "cv：：异常：：异常"
  },
  {
    "origin": "(",
    "local": "("
  },
  {
    "origin": ")",
    "local": ")"
  },
  {
    "origin": "Default constructor",
    "local": "默认构造函数"
  },
  {
    "origin": "&#9670;&nbsp;",
    "local": "&#9670;&nbsp；"
  },
  {
    "origin": "Exception()",
    "local": "异常（）"
  },
  {
    "origin": "[2/2]",
    "local": "[2/2]"
  },
  {
    "origin": "cv::Exception::Exception",
    "local": "cv：：异常：：异常"
  },
  {
    "origin": "(",
    "local": "("
  },
  {
    "origin": "_code",
    "local": "_代码"
  },
  {
    "origin": ",",
    "local": ","
  },
  {
    "origin": "const",
    "local": "常数"
  },
  {
    "origin": "_err",
    "local": "_呃"
  },
  {
    "origin": ",",
    "local": ","
  },
  {
    "origin": "const",
    "local": "常数"
  },
  {
    "origin": "_func",
    "local": "_功能"
  },
  {
    "origin": ",",
    "local": ","
  },
  {
    "origin": "const",
    "local": "常数"
  },
  {
    "origin": "_file",
    "local": "_文件"
  },
  {
    "origin": ",",
    "local": ","
  },
  {
    "origin": "_line",
    "local": "_线路"
  },
  {
    "origin": ")",
    "local": ")"
  },
  {
    "origin": "Full constructor. Normally the constructor is not called explicitly. Instead, the macros",
    "local": "完全构造函数。通常不显式调用构造函数。相反，宏"
  },
  {
    "origin": ",",
    "local": ","
  },
  {
    "origin": "and",
    "local": "和"
  },
  {
    "origin": "are used.",
    "local": "使用。"
  },
  {
    "origin": "&#9670;&nbsp;",
    "local": "&#9670;&nbsp；"
  },
  {
    "origin": "~Exception()",
    "local": "~例外（）"
  },
  {
    "origin": "virtual cv::Exception::~Exception",
    "local": "虚拟cv：：异常：：~异常"
  },
  {
    "origin": "(",
    "local": "("
  },
  {
    "origin": ")",
    "local": ")"
  },
  {
    "origin": "throw",
    "local": "扔"
  },
  {
    "origin": "(",
    "local": "("
  },
  {
    "origin": ")",
    "local": ")"
  },
  {
    "origin": "virtual",
    "local": "事实上的"
  },
  {
    "origin": "Member Function Documentation",
    "local": "成员功能文档"
  },
  {
    "origin": "&#9670;&nbsp;",
    "local": "&#9670;&nbsp；"
  },
  {
    "origin": "formatMessage()",
    "local": "格式化消息（）"
  },
  {
    "origin": "void cv::Exception::formatMessage",
    "local": "void cv:：Exception:：formatMessage"
  },
  {
    "origin": "(",
    "local": "("
  },
  {
    "origin": ")",
    "local": ")"
  },
  {
    "origin": "&#9670;&nbsp;",
    "local": "&#9670;&nbsp；"
  },
  {
    "origin": "what()",
    "local": "什么（）"
  },
  {
    "origin": "virtual const char* cv::Exception::what",
    "local": "虚拟常量字符*cv：：异常：：什么"
  },
  {
    "origin": "(",
    "local": "("
  },
  {
    "origin": ")",
    "local": ")"
  },
  {
    "origin": "const",
    "local": "常数"
  },
  {
    "origin": "throw",
    "local": "扔"
  },
  {
    "origin": "(",
    "local": "("
  },
  {
    "origin": ")",
    "local": ")"
  },
  {
    "origin": "virtual",
    "local": "事实上的"
  },
  {
    "origin": "Returns",
    "local": "退换商品"
  },
  {
    "origin": "the error description and the context as a text string.",
    "local": "错误描述和上下文作为文本字符串。"
  },
  {
    "origin": "Examples:",
    "local": "示例："
  },
  {
    "origin": ".",
    "local": "."
  },
  {
    "origin": "Member Data Documentation",
    "local": "成员数据文档"
  },
  {
    "origin": "&#9670;&nbsp;",
    "local": "&#9670;&nbsp；"
  },
  {
    "origin": "code",
    "local": "代码"
  },
  {
    "origin": "int cv::Exception::code",
    "local": "int cv：：异常：：代码"
  },
  {
    "origin": "error code",
    "local": "错误代码"
  },
  {
    "origin": "See also",
    "local": "另请参见"
  },
  {
    "origin": "CVStatus",
    "local": "CVS状态"
  },
  {
    "origin": "&#9670;&nbsp;",
    "local": "&#9670;&nbsp；"
  },
  {
    "origin": "err",
    "local": "呃"
  },
  {
    "origin": "cv::Exception::err",
    "local": "cv:：异常：：错误"
  },
  {
    "origin": "error description",
    "local": "错误描述"
  },
  {
    "origin": "&#9670;&nbsp;",
    "local": "&#9670;&nbsp；"
  },
  {
    "origin": "file",
    "local": "文件"
  },
  {
    "origin": "cv::Exception::file",
    "local": "cv:：异常：：文件"
  },
  {
    "origin": "source file name where the error has occurred",
    "local": "发生错误的源文件名"
  },
  {
    "origin": "&#9670;&nbsp;",
    "local": "&#9670;&nbsp；"
  },
  {
    "origin": "func",
    "local": "功能"
  },
  {
    "origin": "cv::Exception::func",
    "local": "cv:：异常：：函数"
  },
  {
    "origin": "function name. Available only when the compiler supports getting it",
    "local": "函数名。仅当编译器支持获取时才可用"
  },
  {
    "origin": "&#9670;&nbsp;",
    "local": "&#9670;&nbsp；"
  },
  {
    "origin": "line",
    "local": "线"
  },
  {
    "origin": "int cv::Exception::line",
    "local": "int cv：：异常：：行"
  },
  {
    "origin": "line number in the source file where the error has occurred",
    "local": "发生错误的源文件中的行号"
  },
  {
    "origin": "&#9670;&nbsp;",
    "local": "&#9670;&nbsp；"
  },
  {
    "origin": "msg",
    "local": "味精"
  },
  {
    "origin": "cv::Exception::msg",
    "local": "cv:：异常：：消息"
  },
  {
    "origin": "the formatted error message",
    "local": "格式化的错误消息"
  },
  {
    "origin": "Examples:",
    "local": "示例："
  },
  {
    "origin": ".",
    "local": "."
  },
  {
    "origin": "The documentation for this class was generated from the following file:",
    "local": "此类的文档是从以下文件生成的："
  },
  {
    "origin": "opencv2/",
    "local": "打开CV2/"
  },
  {
    "origin": "Generated on Fri Apr 2 2021 11:36:42 for OpenCV by &#160;",
    "local": "2021年4月2日星期五11:36:42为OpenCV生成，&#160；"
  }
]